---
title: "Psytoolkit data processing"
date: "`r Sys.Date()`"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(lubridate)
```

匯入下載的資料壓縮檔

```{r}
## path to the latest downloaded raw data
downloaded_rawdata <- "0_reproduce_training/xinxi_data.zip"
## Check the downloaded data files
datafiles <- unzip(downloaded_rawdata, list = TRUE)
## Check the time of latest data 
subset(datafiles, Name == "data.csv")$Date
## Import data
datarows <- read_csv(unz(downloaded_rawdata,filename = "data.csv")) %>%
## Erase empty responses
    drop_na() %>%
## Remove the time columns
   select(-starts_with("TIME_"))
```

```{r true_statement}
TRUE_state <- datarows %>%
  select("participant",`1_xinxi_Q1:1`:`1_xinxi_Q1:12`) %>%
  pivot_longer(cols = starts_with("1_xinxi_Q1"), names_to = "True_statment", values_to = "rating") %>%
  group_by(participant) %>%
  summarise(True_statement_5 = mean(rating == 5),
            True_statement_4 = mean(rating == 4),
            True_statement_3 = mean(rating == 3),
            True_statement_2 = mean(rating == 2),
            True_statement_1 = mean(rating == 1)) %>%
  pivot_longer(cols = starts_with("True_statement_"), names_to = "Options",values_to = "Percentage") %>%
  group_by(Options) %>%
  summarise(Mean = round(mean(Percentage)*100,1), 
            SD = round(sd(Percentage)*100,1),
            CI_L = round(Mean + qnorm(.025)*SD/sqrt(length(unique(participant))),1),
            CI_U = round(Mean + qnorm(.975)*SD/sqrt(length(unique(participant))),1),
            MIN = min(Percentage),
            MAX = max(Percentage)) %>%
  arrange(desc(Options))

TRUE_state
```


```{r false_statement}
FALSE_state <- datarows %>%
  select("participant",`1_xinxi_Q1:13`:`1_xinxi_Q1:24`) %>%
  pivot_longer(cols = starts_with("1_xinxi_Q1"), names_to = "True_statment", values_to = "rating") %>%
  group_by(participant) %>%
  summarise(False_statement_5 = mean(rating == 5),
            False_statement_4 = mean(rating == 4),
            False_statement_3 = mean(rating == 3),
            False_statement_2 = mean(rating == 2),
            False_statement_1 = mean(rating == 1)) %>%
  pivot_longer(cols = starts_with("False_statement_"), names_to = "Options",values_to = "Percentage") %>%
  group_by(Options) %>%
  summarise(Mean = round(mean(Percentage)*100,1), 
            SD = round(sd(Percentage)*100,1),
            CI_L = round(Mean + qnorm(.025)*SD/sqrt(length(unique(participant))),1),
            CI_U = round(Mean + qnorm(.975)*SD/sqrt(length(unique(participant))),1),
            MIN = min(Percentage),
            MAX = max(Percentage)) %>%
  arrange(desc(Options))

FALSE_state
```


```{r conspiracy}
Conspiracy <- datarows %>%
  select("participant",`1_xinxi_Q1:25`:`1_xinxi_Q1:32`) %>%
  pivot_longer(cols = starts_with("1_xinxi_Q1"), names_to = "True_statment", values_to = "rating") %>%
  group_by(participant) %>%
  summarise(Conspiracy_5 = mean(rating == 5),
            Conspiracy_4 = mean(rating == 4),
            Conspiracy_3 = mean(rating == 3),
            Conspiracy_2 = mean(rating == 2),
            Conspiracy_1 = mean(rating == 1)) %>%
  pivot_longer(cols = starts_with("Conspiracy_"), names_to = "Options",values_to = "Percentage") %>%
  group_by(Options) %>%
  summarise(Mean = round(mean(Percentage)*100,1), 
            SD = round(sd(Percentage)*100,1),
            CI_L = round(Mean + qnorm(.025)*SD/sqrt(length(unique(participant))),1),
            CI_U = round(Mean + qnorm(.975)*SD/sqrt(length(unique(participant))),1),
            MIN = min(Percentage),
            MAX = max(Percentage)) %>%
  arrange(desc(Options))

Conspiracy
```


提取NC資料

```{r NC, message=FALSE, warning=FALSE}
NC_data <- datarows %>% 
  ## 挑出ID及NC資料
  select("participant", starts_with("16_NC"))
```


提取NCC資料


```{r NCC, message=FALSE, warning=FALSE}
NCC_data <- datarows %>% 
  ## 挑出ID及NC資料
  select("participant", starts_with("17_NCC"))
```

轉換為long table

```{r w_to_l}
data_long <- datarows %>% gather("Qtype","Response",-1) %>%
  separate("Qtype",c("Qtype","Qid"),sep = ":") %>%
  ## 標記測謊題
  mutate(LIE = if_else(Qtype=="17_NCC"&(Qid %in%c(18,22,39,43,46)),"Y","N"))
```

小計參與者量表得分

```{r}
data_long %>%
  ## 排除測謊題
  filter(LIE != "Y") %>%
  group_by(Qtype) %>%
  summarise(score = sum(Response))
```

