# 疫情資訊題目 - 附錄

對於以下有關新型冠狀肺炎病毒及疫苗的說法，您目前有何看法？（請依您最直覺的想法直接回答）

## 真實資訊
|題號| 舊題目 | 新題目 | 解譯 |
|---| --- | --- | --- |
|1|已知的首例冠狀病毒病例發生在中國武漢。|最早的冠狀病毒患者來源於中國。|從原題目第1題更改而來，因為原第9題太過簡單。
|2|冠狀病毒主要通過咳嗽和打噴嚏傳播。|AZ與莫德納的疫苗在第一劑接種完，可於接種後第10至12週接種第二劑。|更改為疫苗題。有拿到疫苗接種卡的人會知道。
|3|冠狀病毒對老年人尤其致命。|對流感疫苗有過敏反應，依舊可以接種冠狀病毒的疫苗。|更改為疫苗題。為正確的疫苗資訊題目
|4|發燒是冠狀病毒的潛在症狀。|發燒是感染冠狀病毒的潛在症狀。|為原題目第4題，未做更改。|
|5|冠狀病毒可以通過沒有出現症狀的人傳播。|注射疫苗前不能服用止痛藥(例如，普拿疼)、消炎藥或退燒藥等藥物，因為會降低免疫反應。|更改為疫苗題。為大眾關心的疫苗相關副作用，並放入錯誤抒緩副作用的呈述。
|6|冠狀病毒來自動物。|施打疫苗並不會造成不孕。|更改為疫苗題。有在關注特殊族群如何打疫苗者知道。
|7|冠狀病毒尚無治療方法。|施打完疫苗後身體出現胸痛、心悸或下肢疼痛的狀況是不正常的要盡快就醫。|更改為疫苗題。為接種疫苗後不正常的狀況。
|8|暴露于冠狀病毒後可能需要 14 天才能出現症狀。|感染冠狀病毒後會有14天的潛伏期。|為原題目第8題，通順語句。未做修改。
|9|保持社交距離有助於減緩冠狀病毒的傳播。|若本身有慢性病(例如:高血壓、糖尿病)但控制穩定，依舊可以接種冠狀病毒疫苗。|更改為疫苗題。有在關注特殊族群如何打疫苗者知道。|
|10|康復後有可能對冠狀病毒免疫。|沒有出現症狀的人能傳播冠狀病毒。|新題目，為2021年4 月台灣疫情爆發發時出現的無症狀感染者。
|11|大多數感染冠狀病毒的人會出現輕微症狀。|冠狀病毒患者康復後若沒有做好防疫措施(例：戴口罩、勤洗手)，依舊有可能會再次受到感染。|新題目。為大眾關注的免疫力問題。
|12|冠狀病毒可以通過電梯按鈕和門把手傳播。|若使用家用快篩試劑呈現陽性，需盡快聯繫當地衛生局或撥打1922。|新題目。為2021年6月家用快篩試劑普及的相關資訊題。

## 不實資訊
|題號| 舊題目 | 新題目 | 解譯 |
|---| --- | --- | --- |
|13|冠狀病毒不如普通流感致命。|懷孕婦女不宜接種任何疫苗。|更改為疫苗題主要原因是原題目過於簡單。而目前疫苗在台灣並沒有許多選擇，所以也產生許多不實資訊，但這些資訊卻是會影響到身邊重要他人。|
|14|冠狀病毒可以通過食物污染傳播。|輝瑞、莫德納等mRNA疫苗是帶有遺傳因子的疫苗，會影響人體基因，有高度致命風險。|更改為疫苗題，為原題目對於台灣是比較少見的狀況，以及語意東西方比較不同，所以更改為疫苗基本常識題。
|15|口罩可以保護您免受冠狀病毒的侵害。|若接種完第一劑疫苗，身體就會有百分之百的保護力，不怕受到感染。|更改為疫苗題，為原本題目過於簡單，以至於不用判斷。
|16|流感疫苗可以保護您免受冠狀病毒的侵害。|流感疫苗可以保護一般人感染冠狀病毒。|保留原題目核心，讓語句通順。
|17|冠狀病毒主要影響心臟。|疫苗的副作用可能會導致血栓、心肌炎，所以要打在右手臂遠離心臟，才能降低副作用。|更改為疫苗題，原因是原題目設計於2020，對於冠狀病毒主要影響已經成為常識，故保留類似的概念，但需要花點時間判斷。|
|18|噁心是冠狀病毒的潛在症狀。|注射輝瑞或莫德納疫苗會讓身體產生磁性。|更改為疫苗題，因原題目判斷不易因此改成目前台灣大眾比較注意的問題。|
|19|冠狀病毒不會通過小學適齡兒童傳播。|醫療口罩不能阻隔冠狀變種病毒的侵害，需配戴N95口罩才可以。|為新題目，原因是原題目設計於2020，因資訊過於舊時，所以改為目前台灣較重視的問題。|
|20|冠狀病毒是普通流感的變種。|冠狀病毒更容易在下雨天傳播，所以下雨天儘量不要出門。|為新題目，因原題目過於簡單，容易判斷，故改為另類題目。|
|21|寵物可能會受到冠狀病毒的影響。|冠狀病毒在抵達肺部前會停留在喉嚨四天，如果喝大量的水，並且以溫水加鹽巴或醋來漱口，可以消除病毒。|為新題目，原本題目研究者已證明是事實，所以補上另一種非事實描述的題目。|
|22|只有在您已經生病的情況下，您才能死于冠狀病毒。|配戴兩層醫用口罩的防護力比內層戴醫用口罩、外層戴布料口罩的防謢力好。|為新題目，因原題目在台灣發生疫情，帶走了800人以上，因此社會大眾了解即使沒有生病，感染冠狀病毒依舊會致命。改為口罩的概念理由在於這是外國媒體報導的資訊，被台灣加以誇大，所以大家都認為帶兩個醫療口罩有助於防疫，但這樣的資訊已被科學家反駁。|
|23|感染冠狀病毒的人只能感染 2-3 個人。|暫時沒有嗅覺或味覺，代表你已經感染冠狀病毒。|為新題目，因2020由於疫情剛爆發，所以感染的資料較少，但由於2021年5月台灣爆發本土疫情，對於台灣人來說不可能只感染2到3個人，可能認為都是以上，於是我們改為目前網路上廣為流行的假資訊作為這一次題目。|
|24|乾手器可有效殺死冠狀病毒。|若蔬果表面上有冠狀病毒，食用後並不會感染，可以放心食用。|為新題目，因原題目對於台灣並不受用，乾手器等於烘手機，台灣一般家庭較少有這個設備，故改為天天必須要接觸的食物作為我們這一次的題目。|

## 流言說法

|題號| 舊題目 | 新題目 | 解譯 |
|---| --- | --- | --- |
|1|中國政府發布了冠狀病毒以防止人口過剩。|中國政府發布了冠狀病毒以防止地球人口過剩。|通順語句，未做太大更改。|
|2|冠狀病毒是在實驗室中創建的，因此製藥行業可以銷售疫苗。|冠狀病毒是人類所創造的，用以讓製藥行業銷售疫苗並撈取利益。|通順語句，未做太大更改。|
|3|冠狀病毒是上帝派來懲罰人類的。|冠狀病毒是神派來懲罰人類的。|通順語句，未做太大更改。|
|4|環保人士發布冠狀病毒以減少二氧化碳排放。|臺灣政府不積極購買疫苗，是為了擁護國產疫苗上市。|更改為疫苗題，為台灣地區關注的熱門議題。|
|5|冠狀病毒是美國政府為了擾亂中國而製造的。|冠狀病毒是中國政府為了引發第三次世界大戰而製造的生化武器。|更改為台灣有報導的陰謀論題目|
|6|冠狀病毒是美國故意製造和傳播用以銷售疫苗的。|冠狀病毒是美國為了向全球銷售疫苗，故意製造和傳播的。|保留原意，使語句通順。|
|7|冠狀病毒是從位於中國的加拿大病毒研究實驗室竊取的。|打疫苗會順便植入微型晶片，是有陰謀集團企圖將全人類數據化。|為疫苗題，因此題不易判斷。|
|8|冠狀病毒不是由人類創造的。|日本在台灣剛爆發疫情時贈送台灣疫苗，是為了挑釁中國。|為疫苗題，原因在於日本的確在6/4贈送台灣124萬AZ疫苗，故有許多猜測出現。|