---
title: "My note"
author: "林子渝"
date: "`r Sys.Date()`"
bibliography: ref.bib
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Need for cognition
廣告的訊息訴求方式、訊息正反性、訊息來源可信度與消費者認知需求對廣告效果之影響。
使用高泉豐(1994)所編的「認知需求的概念與測量」，總共 **12 小題**（前測問卷是 18 小題），採用李克特五點量表。
在行銷管理的領域中，不同的認知需求者在觀看廣告時對廣告態度、產品態度、及購買意願皆有所不同，訊息可信度對高低認知需求者都很重要，而低認知需求者較看重正面訊息與感性訴求的訊息；高認知需求者看重反面訊息與理性訴求的訊息。[@AL:10232842-200503-13-1-107-142-a]
從上述可以看出，訊息的呈現方式可能對不同的認知需求而有差異。而廣告訊息相對於本研究的疫情訊息，或許可以從訊息的正反性看出原始論文為何有些高NC大於低NC的假設沒有全部支持的原因，可能就源自於所接觸到的訊息正反性有關，從廣告訊息中，呈現出正面訊息對低NC者較有影響，而若在相同的環境中，多數的疫情資訊來源呈現都是正面訊息，低NC者就有可能比高NC者記得更多的疫情資訊與知識。

## H1a
原始論文中的假設 H1a：高NC者對疫情的正確認識高於低NC者，結果充分支持，原始研究也發現不只高NC者對疫情資訊的知識與信心顯著高於低NC者，高NCC者也與疫情資訊呈正相關，他們也發現，在疫情資訊題中，對真實資訊呈現的題目表現出更高的準確性，原始論文的給出的解釋為對不實資訊，回答"我不知道"，在理智偏向誠實。因此我們在設計疫情資訊題目時，除了按照原始論文的設計外，我們有對疫情資訊做更新，並加入符合時事的疫苗題，題目部份也進行再三確認，預期也會達到顯著的效果。所謂高NC者，也就是較喜歡思考、較喜歡解決複雜的問題，在解決問題時較會注重過程中的人，反之低NC者則相反。所以我們預期高NC者在接收到疫情資訊時，會去思考這些資訊為什麼會導致這結論，也可能去思考、查證疫情資訊的正確性或是來源可靠性，在這其間會比低NC者獲取更多並較正確的疫情資訊，所以高NC者對疫情的正確認識就會高於低NC者。

## H1b

原始論文中的假設 H1b: 高NC者更新疫情資訊的頻率高於低NC者結果顥示為不支持。原始論文使用回歸分析發現 NC 與 COVID-19 相關訊息的搜索頻率並無關係，描述性分析表明，大多數人都會主動搜尋 COVID-19 的相關訊息。
在我們重製的研究中，由於我們是在台灣地區收集樣本，考慮到自從疫情爆發以來，每天都會有中央流行疫情指揮中心的記者會，因此推測大多數人每天至少會有一次更新疫情資訊的機會，所以可能也無法達到顯注差異，可能NC高低對危機資訊的更新頻率就較無相關，反而與政府的宣導力度有關。如果政府的宣導力度不會影響或者是不夠強力，我們預期在這項假設達到顯著。

> 確認因果關係的描述。

