---
title: Boot (2021) Gather其他中英文研究的引用 
author: "謝明翰"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

引言:
2020年疫情爆發之後有陸陸續續的研究想要探討與新冠肺炎有關的知識。其中Boot(2020)等人探討疫情期間不同認知需求的人獲得知識以及尋求資訊管道的研究。與此同時，我們透過Rstudio可重製研究技術，以及利用Psytoolkit網站進行問卷製作，重新探討Boot(2020)的研究。本研究想藉由重製Boot(2021)的研究，進而了解是否因為認知需求的不同與國內民眾對於獲得知識以及尋求資訊管道有關係。藉以透過可重製資料技術，學習量化的資料研究。在文獻回顧的過程中發現，搜尋認知需求的相關文獻時，國內外所使用的認知需量表有差異，我國傾向於使用高泉豐(1994)年對Cacioppo(1984)認知需求量進行中文化的中譯版。另外經由瀏覽過去認知需求的研究以及透過資料蒐集與重製資料過程，也提出與Boot(2021)原研究假設的一些不同看法。研究使用認知需求(Need for cognition)以及認知閉合需求(Need for cognitive closure0)的問卷，均有中英文版本，並透過臉書社群假新聞清潔劑粉絲專業進行審理。


文獻回顧: 在對認知需求(need for congnition)過去的研究上發現國內對於認知需求的研究有許多篇幅偏向行銷與廣告。而在國內認知需求問卷使用，有經由文獻回顧發現國內認知需求量表中譯版高泉豐(1994)，並透過瀏覽後證實此份針對問卷改良的文獻是Cacioppo(1984)的中譯版本，也在不少國內認知需求主題的相關研究被使用。另外在本重製研究透過文獻回顧找出國內外研究也有使用Cacioppo(1984)、高泉豐(1994)，以及Kruglanski的認知閉合需求問卷。











---------------------
本研究重製 @bootGatheringProcessingInterpreting2021 的問卷調查及假設分析，探討台灣地區民眾相信正確及錯誤疫情資訊的認知動機因素。

認知動機是什麼？
1. Need for cognition(認知需求)

認知需求的人喜歡思考的歷程，他們普遍想要了解知識。因此這些人可能會運用不同的管道去獲得知識，並從中判斷資訊的真實度。

問卷來源文獻: @cacioppoNeedCognition1982; 

@cacioppoEfficientAssessmentNeed1984  (# 在Gathering Reference裡面的6.19)


1-1 求與創業警覺性的關係：創業團隊內一致性壓力知覺的調節效果 黃瓊億 Chiung Yi Huang et.al(@cacioppoNeedCognition1982)
1-2.  Chiung Yi Huang et.al(引用 @cacioppoNeedCognition1982)


2. Need for cognitive closure(認知停歇需求)

認知閉合需求的人認為思考主要是為了要解決問題，以及為了消除對於資訊的不確定，所帶來的壓力或不安。


可引用的相關問卷來源文獻: @KruglanskiPsychologicalTheoryTesting1997
                          @Kruglanskiinneedforcognitiveclosure1994
                          @KruglanskiMotivatedclosingofthemind1996(# 在Gathering Reference裡面的9)
                      

2-1. 探索結論需求對獎勵計畫與忠誠度關聯性之影響 (引用 @Kruglanskiinneedforcognitiveclosure1994 )
2-2. 華人開放性與畫作偏好之關係：以認知閉合需求為中介(引用 @Kruglanskiinneedforcognitiveclosure1994)

2-3. 不同決策特質與搜尋時間壓力下部落格設計與使用者滿意度之探討. 
(有引用到，但不確定有沒有權限可以下載)

2-4. 團隊創新氛圍與團隊認知閉合需求對資訊分享與創新績效的影響(@Kruglanskiinneedforcognitiveclosure1994)


3.
@ 0823  國內研究
3-1關於國內引用NC問卷

國外:Cacioppo(1984)
國內: 高泉豐(1994)[將Caciopo(1984)研究進行修訂後，適合國內使用的認知需求問卷]

3-1-1
國內的認知需求研究有用在行銷方面的研究，中國文化大學碩士學位學程論文在研究工具有提出使用Cacioppo等人(1982)認知需求18項量表，並以7點量表的方式使用。但是研究結果以及附錄未看到使用的狀況。

資料來源: 節目型態如何影響廣告效果-以汽車商品為例。

3-1-2

國內對於廣告所使用的技術，包含(訴求的方式、正反姓、來源度)與消費者認知需求之關係研究。
研究目的:
想知道廣告主應如何運用廣告訊息策略來達到較佳的廣告效果。

設立的假設:
在許多假設上是針對行銷的技術，而又額外的探討消費者的認知需求對廣告的效果。

問卷使用與Boot(2021)尋找的國內引用:

此篇與認知需求對於媒體資訊使用較無關聯，不過研究者也採用了以Cacioppo and Petty（1982）及高泉豐（1994）所建構的量表，總共12小題（前測問卷是18小題），並採用李克氏5點量表。
錯誤: 正式使用的題數並未在研究中提及

資訊來源:廣告的訊息訴求方式、訊息正反性、訊息來源可信度與消費者認知需求對廣告效果之影響 

3-2
NCC問卷

國外:@KruglanskiNFCscale(2013)
國內:尚未發現

NCC(認知閉合需求)

目前看到的認知閉合相關國內研究，主題篇瑜在廣告或行銷方面的研究，廣告研究有的像是探討消費者的認知閉合與創意廣告的關係，以及認知閉合與創業的關係，創業的主題則認為創業警覺性以及個體所知覺到的團隊內一致性壓力，與創業有關係。
閉合需求與虛擬經驗組合的研究，這篇研究探討人在虛擬模擬的人際互動狀態下，他們的認知閉合需求與廣告行銷的關係

引用來源：
渴望延遲閉合需求對創意廣告效果之影響（方菁容、衛萬里、鄧成連）
認知閉合需求與創業警覺性的關係：創業團隊內一致性壓力知覺的調節效果（王瓊億、王預萱）
結論需求與組合順序對虛擬經驗組合之廣告效果影響（耿慶瑞、丁慧瑩、李武軒）
這些文獻也有提到使用Roet and Van Hiel (2011) 的認知閉合量表

-----------------------------

##認知需求與媒體使用相關研究。

(1)
 這是一個中國在線調查，屬於網路研究，Yan Su(2021)等人進行一項來自中國的在線調查 (N = 731)，並研究了中國和國際社交媒體使用對 COVID-19 陰謀論認可  (CTE)的條件性間接影響。其中裡面有提及認知需求程度的不同可能也是一個間接影響陰謀論認可的原因。
 假設共有四個以及三個研究問題。其中研究假設四則提到，參與者認知需求的程度是否會影響陰謀論的支持。
 並無使用與Boot(2021)相關的問卷

(2)
另一個研究也是考慮NFC(認知需求)與主流新聞曝光的探討，研究目的是想知道以認知需求為中介變項的介入，和主流媒體懷疑與主流曝光的關係。Yariv Tsfati(2005)et.al等學者在這份研究提及三個假設。

研究假設:
假設1: 主流媒體懷疑與主流媒體曝光降低互有關係。
假設2: 認知需求將與主流媒體曝光有正相關。
假設3: 新聞媒體的懷疑在影響主流新聞媒體曝光時會與NFC互動。  NFC水平高的媒體懷疑的影響會減弱，NFC水平低的媒體懷疑的影響會更強

附註: 研究皆有使用Cacioppo (1982)，與本次Boot(2021)重製研究較無關，也沒有使用到認知需求問卷。
資料來源: 
(1)Who endorses conspiracy theories? A moderated mediation model of Chinese and international social media use, media skepticism, need for cognition, and COVID-19 conspiracy theory endorsement in China.

(2)Why Do People Watch News They Do Not Trust? The Need for Cognition as a
Moderator in the Association Between News Media Skepticism and Exposure.


來源期刊:Computers in Human Behavior Volume 120, July 2021, 106760
         MEDIA PSYCHOLOGY, 7, 251–271
         
         
         
         
         
         
----- 以下是找過，但沒有引用上述文獻的研究

1
@ 0806 以下是 NCC 沒有引用 Kruglanski (1994),(1996),(1997) 的文獻

1. 認知重評與認知閉合需求間交互作用對心理健康的影響

3.態度一致性與情緒喚起對線上謠言判斷之影響

4. 特別，不知道有沒有權限可以瀏覽 (香港城市大學)

選擇性接觸, 擴展性接觸, 旁導性接觸: 互聯網時代媒體信息接觸理論分析