---
title: Boot (2021) Gather其他中文研究的引用 
author: "謝明翰"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

本研究重製 @bootGatheringProcessingInterpreting2021 的問卷調查及假設分析，探討台灣地區民眾相信正確及錯誤疫情資訊的認知動機因素。

認知動機是什麼？
1. Need for cognition(認知需求)

認知需求的人喜歡思考的歷程，他們普遍想要了解知識。因此這些人可能會運用不同的管道去獲得知識，並從中判斷資訊的真實度。

問卷來源文獻: @cacioppoNeedCognition1982; 

@cacioppoEfficientAssessmentNeed1984  (# 在Gathering Reference裡面的6.19)

1-1 求與創業警覺性的關係：創業團隊內一致性壓力知覺的調節效果 黃瓊億 Chiung Yi Huang et.al(@cacioppoNeedCognition1982)
1-2. 團隊安全感氛圍與團隊認知閉合需求對資訊分享與創新績效的影響 Chiung Yi Huang et.al(引用 @cacioppoNeedCognition1982)

2. Need for cognitive closure(認知停歇需求)

認知閉合需求的人認為思考主要是為了要解決問題，以及為了消除對於資訊的不確定，所帶來的壓力或不安。


可引用的相關問卷來源文獻: @KruglanskiPsychologicalTheoryTesting1997
                          @Kruglanskiinneedforcognitiveclosure1994
                          @KruglanskiMotivatedclosingofthemind1996(# 在Gathering Reference裡面的9)
                      

2-1. 探索結論需求對獎勵計畫與忠誠度關聯性之影響 (引用 @Kruglanskiinneedforcognitiveclosure1994 )
2-2. 華人開放性與畫作偏好之關係：以認知閉合需求為中介(引用 @Kruglanskiinneedforcognitiveclosure1994)

2-3. 不同決策特質與搜尋時間壓力下部落格設計與使用者滿意度之探討. 
(有引用到，但不確定有沒有權限可以下載)

2-4. 團隊創新氛圍與團隊認知閉合需求對資訊分享與創新績效的影響(@Kruglanskiinneedforcognitiveclosure1994)
2-5. 探索結論需求對獎勵計畫與忠誠度關聯性之影響  (@Kruglanskiinneedforcognitiveclosure1994)


3.
@ 0823  國內研究
NC(認知需求)

3-1-1
國內的認知需求研究有用在行銷方面的研究，中國文化大學碩士學位學程論文在研究工具有提出使用Cacioppo等人(1982)認知需求18項量表，並以7點量表的方式使用。但是研究結果以及附錄未看到使用的狀況。

資料來源: 節目型態如何影響廣告效果-以汽車商品為例。

3-1-2

國內對於廣告所使用的技術，包含(訴求的方式、正反姓、來源度)與消費者認知需求之關係研究。
研究目的:
想知道廣告主應如何運用廣告訊息策略來達到較佳的廣告效果。

設立的假設:
在許多假設上是針對行銷的技術，而又額外的探討消費者的認知需求對廣告的效果。

問卷使用與Boot(2021)尋找的國內引用:

此篇與認知需求對於媒體資訊使用較無關聯，不過研究者也採用了以Cacioppo and Petty（1982）及高泉豐（1994）所建構的量表，總共12小題（前測問卷是18小題），並採用李克氏5點量表。
錯誤: 正式使用的題數並未在研究中提及

資訊來源:廣告的訊息訴求方式、訊息正反性、訊息來源可信度與消費者認知需求對廣告效果之影響 




NCC(認知閉合需求)

目前看到的認知閉合相關國內研究，在許多廣告研究都能看見，其中包含，消費者的認知閉合與創意廣告的關係（消費者的認知閉合需求，在看到商業廣告，與他們的認知閉合需求的關係），以及認知閉合與創業的關係，此研究認為創業警覺性以及個體所知覺到的團隊內一致性壓力，與創業有關係。
閉合需求與虛擬經驗組合的研究，這篇研究探討人在虛擬模擬的人際互動狀態下，他們的認知閉合需求與廣告行銷的關係

引用來源：
渴望延遲閉合需求對創意廣告效果之影響（方菁容、衛萬里、鄧成連）
認知閉合需求與創業警覺性的關係：創業團隊內一致性壓力知覺的調節效果（王瓊億、王預萱）
結論需求與組合順序對虛擬經驗組合之廣告效果影響（耿慶瑞、丁慧瑩、李武軒）
這些文獻也有提到使用Roet and Van Hiel (2011) 的認知閉合量表





----- 以下是找過，但沒有引用上述文獻的研究

1
@ 0806 以下是 NCC 沒有引用 Kruglanski (1994),(1996),(1997) 的文獻

1. 認知重評與認知閉合需求間交互作用對心理健康的影響

3.態度一致性與情緒喚起對線上謠言判斷之影響

4. 特別，不知道有沒有權限可以瀏覽 (香港城市大學)

選擇性接觸, 擴展性接觸, 旁導性接觸: 互聯網時代媒體信息接觸理論分析

@ 關於國內引用NC問卷
引用的問卷:國外Cacioppo(1984)
           國內 高泉豐(1994)[將Caciopo(1984)研究進行修訂後，適合國內使用的認知需求問卷]


NC

 1.1
 廣告的訊息訴求方式、訊息正反性、訊息來源可信度與消費者認知需求對廣告效果之影響 


國內對於廣告所使用的技術，包含(訴求的方式、正反姓、來源度)與消費者認知需求之關係研究。

研究目的:
想知道廣告主應如何運用廣告訊息策略來達到較佳的廣告效果。

設立的假設:
在許多假設上是針對行銷的技術，而又額外的探討消費者的認知需求對廣告的效果。

問卷使用與Boot(2021)尋找的國內引用:

此篇與認知需求對於媒體資訊使用較無關聯，不過研究者也採用了以Cacioppo and Petty（1982）及高泉豐（1994）所建構的量表，總共12小題（前測問卷是18小題），並採用李克氏5點量表。

錯誤: 正式使用的題數並未在研究中提及


