---
title: "重製研究規劃"
date: "`r Sys.Date()`"
output: html_document
---
  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(osfr)
```


### 下載原始資料

原始資料下載處： https://osf.io/a9qsy


```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
## Get the meta from OSF
pl_project <- osf_retrieve_node("a9qsy")
origin_files <- osf_ls_files(pl_project)

if(sum((origin_files %>% filter( grepl(".csv$|.xlsx$|rmd",name)))$name %in% as.numeric(list.files(pattern = ".csv$|.xlsx$|rmd")))  != 7){
  ## Download the csv, excel, and Rmd files
origin_files %>% filter( grepl(".csv$|.xlsx$|rmd",name)) %>%
  osf_download()
} else{
  print("all files were downloaded")
}
```


```{r}
list.files(pattern="Subject_Dataset_Codebook.csv") %>%
  read_csv() %>%
  rmarkdown::paged_table(options = list(rows.print = 20))
```


### 重製規劃

- [計畫書源始檔](1_proposal.Rmd)

- [考驗力模擬分析](2_power_simulation.html)

- [OpenSesame腳本:更新中](../1_OS_scripts/ReplicationKerweretal2021_3.3.10.osexp)

  - [腳本測試網頁](https://cortex.jatos.org/publix/162/start?batchId=163&generalMultiple) ~ 只使用滑鼠就能完成全部問題
  - [OpenSesame 3.3.10版下載](https://github.com/open-cogsci/OpenSesame/releases/download/prerelease%2F3.3.10a12/opensesame_3.3.10a12-py37-win64-2.exe)